"""
Shared Memory - Shared State Management

All agents communicate through SharedState, avoiding state coupling.
This module defines the data structures and state container used across
the entire AIOps agent system.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum
from datetime import datetime
import uuid


class IncidentStatus(str, Enum):
    """
    Enumeration of incident lifecycle states.

    Defines all possible states an incident can be in during the
    AIOps processing pipeline. Used for state machine transitions
    and progress tracking.

    States:
        PENDING: Initial state, incident not yet processed
        DETECTING: Detection agent is analyzing observability data
        DIAGNOSING: Diagnosis agent is identifying root cause
        DECIDING: Decision agent is determining remediation strategy
        REPAIRING: Repair agent is executing remediation
        VERIFYING: Verification of repair success
        RESOLVED: Incident successfully resolved
        ESCALATED: Incident requires human intervention
    """
    PENDING = "pending"
    DETECTING = "detecting"
    DIAGNOSING = "diagnosing"
    DECIDING = "deciding"
    REPAIRING = "repairing"
    VERIFYING = "verifying"
    RESOLVED = "resolved"
    ESCALATED = "escalated"


class RepairMode(str, Enum):
    """
    Enumeration of repair execution modes.

    Determines how repair operations are executed and approved.

    Modes:
        AUTO: Fully automatic execution, no human approval required
        MANUAL: Requires explicit human approval before execution
        HYBRID: Automatic for low-risk, manual for high-risk actions
    """
    AUTO = "auto"
    MANUAL = "manual"
    HYBRID = "hybrid"


@dataclass
class ObservabilityData:
    """
    Multi-modal observability data container.

    Holds collected and processed data from monitoring systems including
    metrics, logs, and traces. This is the primary input for anomaly
    detection and root cause analysis.

    Attributes:
        metrics (List[Dict[str, Any]]): Time-series metric data points
            from Prometheus or similar monitoring systems. Each dict
            contains metric name, labels, values, and timestamps.
        logs (List[Dict[str, Any]]): Log entries from Loki or ELK.
            Each dict contains timestamp, level, service, message,
            and parsed template/parameters.
        traces (List[Dict[str, Any]]): Distributed trace spans from
            Jaeger or Tempo. Each dict contains trace_id, span_id,
            service, operation, duration, and status.
        summary (str): Human-readable summary of the observability
            data, generated by the Observability Agent.
        time_range (Dict[str, datetime]): Time window for data
            collection with 'start' and 'end' keys.

    Example:
        ```python
        obs_data = ObservabilityData(
            metrics=[
                {"name": "cpu_usage", "value": 95.2, "pod": "api-1"}
            ],
            logs=[
                {"level": "ERROR", "message": "Connection timeout"}
            ],
            time_range={
                "start": datetime(2024, 1, 1, 10, 0),
                "end": datetime(2024, 1, 1, 10, 5)
            }
        )
        ```
    """
    metrics: List[Dict[str, Any]] = field(default_factory=list)
    logs: List[Dict[str, Any]] = field(default_factory=list)
    traces: List[Dict[str, Any]] = field(default_factory=list)
    summary: str = ""
    time_range: Dict[str, datetime] = field(default_factory=dict)


@dataclass
class AnomalyEvent:
    """
    Anomaly event representation.

    Represents a detected anomaly with all relevant metadata including
    type, severity, confidence, and affected entities. This is the
    output of the Detection Agent and input to Diagnosis Agent.

    Attributes:
        id (str): Unique identifier for this anomaly event
        type (str): Classification of anomaly (e.g., "cpu_spike",
            "latency_increase", "error_rate", "memory_leak")
        severity (str): Severity level - LOW, MEDIUM, HIGH, CRITICAL
        confidence (float): Detection confidence score [0.0, 1.0]
        affected_entities (List[str]): List of affected services,
            pods, or infrastructure components
        time_window (Dict[str, datetime]): Time range when anomaly
            was detected with 'start' and 'end' keys
        evidence (Dict[str, Any]): Raw evidence data supporting the
            detection, including metric values and log patterns
        is_confirmed (bool): Whether a human has confirmed this
            is a true positive
        human_feedback (Optional[str]): Optional feedback from
            human operator confirming or rejecting the detection

    Example:
        ```python
        anomaly = AnomalyEvent(
            type="cpu_spike",
            severity="HIGH",
            confidence=0.92,
            affected_entities=["api-service-pod-1", "api-service-pod-2"],
            evidence={
                "metric": "container_cpu_usage",
                "threshold": 80.0,
                "actual": 95.2
            }
        )
        ```
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    type: str = ""
    severity: str = "LOW"
    confidence: float = 0.0
    affected_entities: List[str] = field(default_factory=list)
    time_window: Dict[str, datetime] = field(default_factory=dict)
    evidence: Dict[str, Any] = field(default_factory=dict)
    is_confirmed: bool = False
    human_feedback: Optional[str] = None


@dataclass
class RootCauseAnalysis:
    """
    Root cause analysis result container.

    Contains the output from the Diagnosis Agent including identified
    root causes, propagation paths, and supporting evidence.

    Attributes:
        root_causes (List[Dict[str, Any]]): List of identified root
            causes. Each dict contains 'entity', 'cause', 'confidence',
            and 'evidence' keys.
        propagation_path (List[str]): Sequence of entities showing
            how the fault propagated through the system
        confidence (float): Overall confidence in the analysis [0.0, 1.0]
        evidence_chain (List[str]): Human-readable chain of evidence
            supporting the conclusion
        impact_scope (Dict[str, Any]): Description of impact including
            affected services, users, and business metrics
        is_verified (bool): Whether the analysis has been verified

    Example:
        ```python
        rca = RootCauseAnalysis(
            root_causes=[
                {
                    "entity": "database-primary",
                    "cause": "Connection pool exhaustion",
                    "confidence": 0.87
                }
            ],
            propagation_path=[
                "database-primary",
                "api-service",
                "frontend-service"
            ],
            evidence_chain=[
                "DB connection pool at 100% capacity",
                "API latency increased 5x at same time",
                "Error logs show connection timeout"
            ]
        )
        ```
    """
    root_causes: List[Dict[str, Any]] = field(default_factory=list)
    propagation_path: List[str] = field(default_factory=list)
    confidence: float = 0.0
    evidence_chain: List[str] = field(default_factory=list)
    impact_scope: Dict[str, Any] = field(default_factory=dict)
    is_verified: bool = False


@dataclass
class DecisionPackage:
    """
    Decision instruction package.

    Contains the remediation strategy determined by the Decision Agent.
    This is consumed by the Repair Agent for execution.

    Attributes:
        strategy (str): High-level remediation strategy description
        actions (List[Dict[str, Any]]): Ordered list of actions to
            execute. Each dict contains 'type', 'target', 'parameters',
            and 'expected_outcome' keys.
        risk_level (str): Risk assessment - LOW, MEDIUM, HIGH
        estimated_recovery_time (str): Expected time to restore service
        rollback_plan (str): Steps to rollback if repair fails
        confidence (float): Confidence in the decision [0.0, 1.0]
        requires_approval (bool): Whether human approval is required
            before execution

    Example:
        ```python
        decision = DecisionPackage(
            strategy="Restart affected pods and scale up database",
            actions=[
                {
                    "type": "k8s_restart",
                    "target": "api-service-pod-1",
                    "parameters": {}
                },
                {
                    "type": "k8s_scale",
                    "target": "database-pool",
                    "parameters": {"replicas": 3}
                }
            ],
            risk_level="MEDIUM",
            estimated_recovery_time="5 minutes",
            rollback_plan="Restore from latest backup",
            requires_approval=True
        )
        ```
    """
    strategy: str = ""
    actions: List[Dict[str, Any]] = field(default_factory=list)
    risk_level: str = "LOW"
    estimated_recovery_time: str = ""
    rollback_plan: str = ""
    confidence: float = 0.0
    requires_approval: bool = False


@dataclass
class RepairState:
    """
    Repair execution state tracker.

    Tracks the progress and status of repair operations executed by
    the Repair Agent.

    Attributes:
        mode (RepairMode): Current execution mode (AUTO/MANUAL/HYBRID)
        status (str): Current status - pending, running, success,
            failed, waiting_approval
        executed_actions (List[Dict[str, Any]]): List of actions
            already executed with their results
        pending_approval (Optional[Dict[str, Any]]): Action details
            waiting for human approval, None if none pending
        result (Optional[str]): Final result description

    Example:
        ```python
        repair = RepairState(
            mode=RepairMode.HYBRID,
            status="waiting_approval",
            executed_actions=[
                {"action": "restart_pod", "result": "success"}
            ],
            pending_approval={
                "action": "scale_database",
                "risk": "MEDIUM"
            }
        )
        ```
    """
    mode: RepairMode = RepairMode.AUTO
    status: str = "pending"
    executed_actions: List[Dict[str, Any]] = field(default_factory=list)
    pending_approval: Optional[Dict[str, Any]] = None
    result: Optional[str] = None


@dataclass
class ExperienceRecord:
    """
    GRPO experience record for learning.

    Records a complete incident resolution experience for future
    reference and strategy optimization via RAG retrieval.

    Attributes:
        incident_id (str): Reference to the original incident
        anomaly_type (str): Type of anomaly that occurred
        root_cause (str): Identified root cause
        action_taken (str): Remediation action that was executed
        outcome (str): Result - 'success' or 'failure'
        reward (float): Reward score [0.0, 1.0] based on outcome
            and efficiency
        timestamp (datetime): When this experience was recorded

    Example:
        ```python
        record = ExperienceRecord(
            incident_id="inc-12345",
            anomaly_type="cpu_spike",
            root_cause="Connection pool exhaustion",
            action_taken="Restarted pods and scaled database",
            outcome="success",
            reward=0.9
        )
        ```
    """
    incident_id: str
    anomaly_type: str
    root_cause: str
    action_taken: str
    outcome: str
    reward: float = 0.0
    timestamp: datetime = field(default_factory=datetime.now)


class SharedState:
    """
    Shared state container for inter-agent communication.

    All agents read from and write to this shared state, enabling
    coordination without direct coupling. This is the central data
    structure that flows through the LangGraph workflow.

    Attributes:
        incident_id (str): Unique identifier for this incident
        status (IncidentStatus): Current lifecycle stage
        created_at (datetime): When the incident was first recorded
        updated_at (datetime): Last update timestamp
        observability (ObservabilityData): Collected monitoring data
        anomaly (AnomalyEvent): Detected anomaly details
        diagnosis (RootCauseAnalysis): Root cause analysis results
        decision (DecisionPackage): Remediation decision
        repair (RepairState): Repair execution state
        experience_records (List[ExperienceRecord]): Historical
            experiences for GRPO retrieval
        human_feedback (Optional[str]): Any human operator feedback
        intervention_requested (bool): Whether human help was requested
        errors (List[str]): List of errors encountered
        logs (List[str]): Chronological log of all operations

    Example:
        ```python
        # Create new state
        state = SharedState()

        # Access in agents
        state.observability = observability_data
        state.anomaly = detected_anomaly
        state.status = IncidentStatus.DIAGNOSING

        # Convert for LangGraph
        state_dict = state.to_dict()
        ```
    """

    def __init__(self, incident_id: Optional[str] = None):
        """
        Initialize a new shared state container.

        Args:
            incident_id (Optional[str]): Optional incident ID. If not
                provided, a new UUID will be generated.
        """
        self.incident_id = incident_id or str(uuid.uuid4())
        self.status = IncidentStatus.PENDING
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

        # Stage-specific data
        self.observability: Optional[ObservabilityData] = None
        self.anomaly: Optional[AnomalyEvent] = None
        self.diagnosis: Optional[RootCauseAnalysis] = None
        self.decision: Optional[DecisionPackage] = None
        self.repair: RepairState = RepairState()

        # GRPO experience records
        self.experience_records: List[ExperienceRecord] = field(default_factory=list)

        # Human interaction
        self.human_feedback: Optional[str] = None
        self.intervention_requested: bool = False

        # Error handling and logging
        self.errors: List[str] = []
        self.logs: List[str] = []

    def log(self, message: str):
        """
        Add a timestamped log entry.

        Args:
            message (str): Message to log
        """
        self.logs.append(f"[{datetime.now().isoformat()}] {message}")

    def add_error(self, error: str):
        """
        Record an error and add it to logs.

        Args:
            error (str): Error message to record
        """
        self.errors.append(error)
        self.log(f"ERROR: {error}")

    def update(self):
        """Update the timestamp to current time."""
        self.updated_at = datetime.now()

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert state to dictionary for LangGraph compatibility.

        Returns:
            Dict[str, Any]: Dictionary representation of all state
        """
        return {
            "incident_id": self.incident_id,
            "status": self.status.value,
            "observability": self.observability,
            "anomaly": self.anomaly,
            "diagnosis": self.diagnosis,
            "decision": self.decision,
            "repair": self.repair,
            "human_feedback": self.human_feedback,
            "errors": self.errors,
            "logs": self.logs,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SharedState":
        """
        Create SharedState from dictionary.

        Args:
            data (Dict[str, Any]): Dictionary with state data

        Returns:
            SharedState: Reconstructed state object
        """
        state = cls(incident_id=data.get("incident_id"))
        state.status = IncidentStatus(data.get("status", "pending"))
        state.observability = data.get("observability")
        state.anomaly = data.get("anomaly")
        state.diagnosis = data.get("diagnosis")
        state.decision = data.get("decision")
        state.repair = data.get("repair", RepairState())
        state.human_feedback = data.get("human_feedback")
        state.errors = data.get("errors", [])
        state.logs = data.get("logs", [])
        return state


# LangGraph compatible state alias
AgentState = Dict[str, Any]
